//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectControlPST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetsForRequest
    {
        public int uniqueId { get; set; }
        public Nullable<int> idAssetsList { get; set; }
        public Nullable<int> idTypeRequest { get; set; }
    
        public virtual AssetsList AssetsList { get; set; }
        public virtual TypeRequest TypeRequest { get; set; }
    }
}
