//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectControlPST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDescription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectDescription()
        {
            this.AssetProjects = new HashSet<AssetProject>();
            this.Domains = new HashSet<Domain>();
            this.EffectedURLs = new HashSet<EffectedURL>();
            this.ThirdPartyCredentials = new HashSet<ThirdPartyCredential>();
            this.WorkOrders = new HashSet<WorkOrder>();
        }
    
        public int uniqueId { get; set; }
        public string projectDescription1 { get; set; }
        public Nullable<System.DateTime> kickOffDate { get; set; }
        public Nullable<System.DateTime> liveDate { get; set; }
        public string targetDevice { get; set; }
        public string platform { get; set; }
        public string seoAnalytics { get; set; }
        public string additionalComments { get; set; }
        public int idWorkOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetProject> AssetProjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Domain> Domains { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EffectedURL> EffectedURLs { get; set; }
        public virtual WorkOrder WorkOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThirdPartyCredential> ThirdPartyCredentials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrder> WorkOrders { get; set; }
    }
}
