//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectControlPST.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PSTProjectControlEntities : DbContext
    {
        public PSTProjectControlEntities()
            : base("name=PSTProjectControlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssetProject> AssetProjects { get; set; }
        public virtual DbSet<AssetsForRequest> AssetsForRequests { get; set; }
        public virtual DbSet<AssetsList> AssetsLists { get; set; }
        public virtual DbSet<Domain> Domains { get; set; }
        public virtual DbSet<EffectedURL> EffectedURLs { get; set; }
        public virtual DbSet<ProjectDescription> ProjectDescriptions { get; set; }
        public virtual DbSet<ProjectStatu> ProjectStatus { get; set; }
        public virtual DbSet<ThirdPartyCredential> ThirdPartyCredentials { get; set; }
        public virtual DbSet<TypeRequest> TypeRequests { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WorkOrder> WorkOrders { get; set; }
        public virtual DbSet<vw_assets_project> vw_assets_project { get; set; }
        public virtual DbSet<vw_workOrder_description> vw_workOrder_description { get; set; }
        public virtual DbSet<vw_typerequest_assets> vw_typerequest_assets { get; set; }
    }
}
