//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectControlPST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_assets_project
    {
        public int assetProjectId { get; set; }
        public int assetListId { get; set; }
        public string asset { get; set; }
        public bool value { get; set; }
        public Nullable<int> idProjectDescription { get; set; }
    }
}
