//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectControlPST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_workOrder_description
    {
        public int uniqueId { get; set; }
        public string author { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public int idTypeRequest { get; set; }
        public string projectName { get; set; }
        public Nullable<int> referencePreviousJob { get; set; }
        public string agencyPM { get; set; }
        public string agencyAccountDirector { get; set; }
        public string brandManager { get; set; }
        public string prodigiousPM { get; set; }
        public string secureCode { get; set; }
        public string jiraParentUrl { get; set; }
        public int idProjectStatus { get; set; }
        public Nullable<int> idProjectDescription { get; set; }
        public int idUser { get; set; }
        public string request { get; set; }
        public string status { get; set; }
        public string projectDescription { get; set; }
        public Nullable<System.DateTime> kickOffDate { get; set; }
        public Nullable<System.DateTime> liveDate { get; set; }
        public string targetDevice { get; set; }
        public string platform { get; set; }
        public string seoAnalytics { get; set; }
        public string additionalComments { get; set; }
    }
}
